version: '2'

services:
  oracle-xe:
    image: oracleinanutshell/oracle-xe-11g
    ports:
      - 1521:1521
      - 18080:8080
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=true 
      - ORACLE_ENABLE_XDB=true
